up, only one packages now

diff --git a/debian/crowdsec-firewall-bouncer-iptables.postinst b/debian/crowdsec-firewall-bouncer-iptables.postinst
--- a/debian/crowdsec-firewall-bouncer-iptables.postinst
+++ b/debian/crowdsec-firewall-bouncer-iptables.postinst
@@ -1,8 +1,42 @@
 
+systemctl daemon-reload
+
+
+START=0
 
 if [ "$1" = "configure" ] && [ "$2" = "" ]; then
+
+    type cscli > /dev/null
+
+    if [ "$?" -eq "0" ] ; then
+        START=1
+        echo "cscli/crowdsec is present, generating API key"
+        unique=`date +%s`
+        API_KEY=`cscli -oraw bouncers add FirewallBouncer-${unique}`
+        if [ $? -eq 1 ] ; then
+            echo "failed to create API token, service won't be started."
+            START=0
+            API_KEY="<API_KEY>"
+        else
+            echo "API Key : ${API_KEY}"
+        fi
+    fi
+
     TMP=`mktemp -p /tmp/`
     cp /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml ${TMP}
-    BACKEND=iptables API_KEY='${API_KEY}' envsubst < ${TMP} > /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
+    BACKEND=iptables API_KEY=${API_KEY} envsubst < ${TMP} > /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
     rm ${TMP}
-fi;
+
+else 
+
+    START=1
+fi
+
+
+
+
+if [ ${START} -eq 0 ] ; then
+    echo "no api key was generated, won't start service"
+else 
+    systemctl start crowdsec-firewall-bouncer
+fi
