fix

diff --git a/debian/crowdsec-firewall-bouncer-nftables.postinst b/debian/crowdsec-firewall-bouncer-nftables.postinst
--- a/debian/crowdsec-firewall-bouncer-nftables.postinst
+++ b/debian/crowdsec-firewall-bouncer-nftables.postinst
@@ -5,34 +5,27 @@ systemctl daemon-reload
 START=0
 
 if [ "$1" = "configure" ]; then
-
-    #we're doing an upgrade, capture the api key
-    if [ "$2" != "" ]; then
-        START=1
-        API_KEY=`cat /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml | grep '^api_key:' | sed  's/api_key: \(.*\)$/\1/'`
-    else
     #otherwise, try to generate an api key
 
-        type cscli > /dev/null
+    type cscli > /dev/null
 
-        if [ "$?" -eq "0" ] ; then
-            START=1
-            echo "cscli/crowdsec is present, generating API key"
-            unique=`date +%s`
-            API_KEY=`cscli -oraw bouncers add FirewallBouncer-${unique}`
-            if [ $? -eq 1 ] ; then
-                echo "failed to create API token, service won't be started."
-                START=0
-                API_KEY="<API_KEY>"
-            else
-                echo "API Key : ${API_KEY}"
-            fi
+    if [ "$?" -eq "0" ] ; then
+        START=1
+        echo "cscli/crowdsec is present, generating API key"
+        unique=`date +%s`
+        API_KEY=`cscli -oraw bouncers add FirewallBouncer-${unique}`
+        if [ $? -eq 1 ] ; then
+            echo "failed to create API token, service won't be started."
+            START=0
+            API_KEY="<API_KEY>"
+        else
+            echo "API Key : ${API_KEY}"
         fi
     fi
 
     TMP=`mktemp -p /tmp/`
     cp /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml ${TMP}
-    BACKEND=iptables API_KEY=${API_KEY} envsubst < ${TMP} > /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
+    BACKEND=nftables API_KEY=${API_KEY} envsubst < ${TMP} > /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
     rm ${TMP}
 
 else 
