Update install/uninstall scripts

diff --git a/debian/crowdsec-firewall-bouncer-nftables.postinst b/debian/crowdsec-firewall-bouncer-nftables.postinst
--- a/debian/crowdsec-firewall-bouncer-nftables.postinst
+++ b/debian/crowdsec-firewall-bouncer-nftables.postinst
@@ -2,44 +2,60 @@
 
 systemctl daemon-reload
 
-START=0
+BACKEND=nftables
+CONFIG=/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
 
-if [ "$1" = "configure" ]; then
+START=1
 
-    if command -v cscli >/dev/null; then
-        START=1
-        echo "cscli/crowdsec is present, generating API key"
-        unique=$(date +%s)
-        API_KEY=$(cscli -oraw bouncers add FirewallBouncer-"$unique")
-        if [ $? -eq 1 ]; then
-            echo "failed to create API token, service won't be started."
-            START=0
-            API_KEY="<API_KEY>"
-        else
-            echo "API Key : ${API_KEY}"
-        fi
+do_configure() {
+    before=$(cat "$CONFIG")
+    # shellcheck disable=SC2016
+    after=$(envsubst '$BACKEND $API_KEY' < "$CONFIG")
+
+    # are both BACKEND and API_KEY already set?
+    if [ "$before" = "$after" ]; then
+        return
     fi
 
-    TMP=$(mktemp -p /tmp/)
-    install -m 0600 /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml "$TMP"
-    BACKEND=nftables API_KEY="$API_KEY" envsubst < "$TMP" | install -m 0600 /dev/stdin /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
-    rm "$TMP"
-else
-    START=1
+    # if we can't set the key, the user will take care of it
+    API_KEY="<API_KEY>"
+
+    if command -v cscli >/dev/null; then
+        echo "cscli/crowdsec is present, generating API key" >&2
+        unique=$(date +%s)
+        bouncer_id="FirewallBouncer-$unique"
+        API_KEY=$(cscli -oraw bouncers add "$bouncer_id")
+        if [ $? -eq 1 ]; then
+            echo "failed to create API token" >&2
+            START=0
+        else
+            echo "API Key: ${API_KEY}" >&2
+            echo "$bouncer_id" > "$CONFIG.id"
+        fi
+    else
+        START=0
+    fi
+
+    # shellcheck disable=SC2016
+    echo "$before" | BACKEND=$BACKEND API_KEY="$API_KEY" envsubst '$BACKEND $API_KEY' | install -m 0600 /dev/stdin "$CONFIG"
+}
+
+if [ "$1" = "configure" ]; then
+    do_configure
 fi
 
 if command -v cscli >/dev/null; then
     PORT=$(cscli config show --key "Config.API.Server.ListenURI" | cut -d ":" -f2)
     if [ "$PORT" != "" ]; then
-       sed -i "s/localhost:8080/127.0.0.1:${PORT}/g" /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
-       sed -i "s/127.0.0.1:8080/127.0.0.1:${PORT}/g" /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
+       sed -i "s/localhost:8080/127.0.0.1:${PORT}/g" "$CONFIG"
+       sed -i "s/127.0.0.1:8080/127.0.0.1:${PORT}/g" "$CONFIG"
     fi
 fi
 
 systemctl --quiet is-enabled crowdsec-firewall-bouncer || systemctl unmask crowdsec-firewall-bouncer && systemctl enable crowdsec-firewall-bouncer
 
 if [ "$START" -eq 0 ]; then
-    echo "no api key was generated, won't start the service"
+    echo "no api key was generated, won't start the service" >&2
 else
     systemctl start crowdsec-firewall-bouncer
 fi
