deb: fixed bouncer removal when purging package

diff --git a/debian/crowdsec-firewall-bouncer-iptables.prerm b/debian/crowdsec-firewall-bouncer-iptables.prerm
--- a/debian/crowdsec-firewall-bouncer-iptables.prerm
+++ b/debian/crowdsec-firewall-bouncer-iptables.prerm
@@ -4,12 +4,5 @@ set -eu
 
 BOUNCER="crowdsec-firewall-bouncer"
 
-#shellcheck source=./scripts/_bouncer.sh
-. "/usr/lib/$DPKG_MAINTSCRIPT_PACKAGE/_bouncer.sh"
-
-systemctl stop "$SERVICE" || echo "cannot stop service"
-systemctl disable "$SERVICE" || echo "cannot disable service"
-
-if [ "$1" = "purge" ]; then
-    delete_bouncer
-fi
+systemctl stop "$BOUNCER" || echo "cannot stop service"
+systemctl disable "$BOUNCER" || echo "cannot disable service"
